// Store catalog — neutral typographic treatment, no real logos/brand marks.
// Names are factual references to Spanish grocery retailers.
const STORES = [
  { id: 'merc', name: 'Mercadona',       mark: 'M', hue: 90,  delivery: 4.90, minFree: 50, eta: '2h', coverage: 0.98 },
  { id: 'carr', name: 'Carrefour',       mark: 'C', hue: 25,  delivery: 3.50, minFree: 45, eta: '90m', coverage: 0.95 },
  { id: 'lidl', name: 'Lidl',            mark: 'L', hue: 220, delivery: 4.50, minFree: 60, eta: '3h', coverage: 0.72 },
  { id: 'dia',  name: 'Día',             mark: 'D', hue: 0,   delivery: 2.99, minFree: 40, eta: '2h', coverage: 0.88 },
  { id: 'eci',  name: 'El Corte Inglés', mark: 'E', hue: 200, delivery: 5.90, minFree: 75, eta: '1h', coverage: 0.90 },
  { id: 'amz',  name: 'Amazon Fresh',    mark: 'A', hue: 40,  delivery: 0,    minFree: 0,  eta: '2h', coverage: 0.65, note: 'prime' },
  { id: 'sco',  name: 'Supercor',        mark: 'S', hue: 160, delivery: 4.20, minFree: 50, eta: '90m', coverage: 0.80 },
];

// Core catalog — each product has per-store pricing and metadata.
// Prices in EUR. Seasonality + white-label alternatives baked in where relevant.
const CATALOG = {
  leche: {
    id: 'leche', category: 'frescos',
    name: { es: 'Leche entera', en: 'Whole milk' },
    unit: { es: '6 × 1 L', en: '6 × 1 L' },
    emoji: '🥛',
    prices: { merc: 7.14, carr: 7.49, lidl: 6.90, dia: 7.20, eci: 8.40, amz: 7.80, sco: 7.95 },
    history: [7.40, 7.35, 7.28, 7.22, 7.18, 7.14], // 6 months, mercadona
    whiteLabel: { name: { es: 'Hacendado entera', en: 'Hacendado whole' }, save: 0.84 },
    tag: { es: 'Básico', en: 'Staple' },
  },
  naranjas: {
    id: 'naranjas', category: 'frescos',
    name: { es: 'Naranjas Navelina', en: 'Navelina oranges' },
    unit: { es: '2 kg', en: '2 kg' },
    emoji: '🍊',
    prices: { merc: 2.98, carr: 3.40, lidl: 2.79, dia: 3.10, eci: 4.20, amz: 3.60, sco: 3.80 },
    history: [4.20, 3.90, 3.50, 3.20, 3.05, 2.98],
    seasonal: { es: 'En temporada — pico de dulzor hasta abril', en: 'In season — peak sweetness through April' },
    tag: { es: 'Temporada', en: 'In season' },
  },
  manzanas: {
    id: 'manzanas', category: 'frescos',
    name: { es: 'Manzanas Golden', en: 'Golden apples' },
    unit: { es: '1 kg', en: '1 kg' },
    emoji: '🍎',
    prices: { merc: 1.89, carr: 2.10, lidl: 1.75, dia: 1.95, eci: 2.60, amz: 2.20, sco: 2.40 },
    history: [2.10, 2.05, 2.00, 1.95, 1.92, 1.89],
    seasonal: { es: 'Mejor momento ahora — cosecha tardía', en: 'Peak right now — late harvest' },
    tag: { es: 'Temporada', en: 'In season' },
  },
  aceite: {
    id: 'aceite', category: 'despensa',
    name: { es: 'Aceite oliva virgen extra', en: 'Extra virgin olive oil' },
    unit: { es: '1 L', en: '1 L' },
    emoji: '🫒',
    prices: { merc: 7.85, carr: 8.20, lidl: 7.50, dia: 7.99, eci: 9.40, amz: 8.60, sco: 8.80 },
    history: [11.20, 10.40, 9.60, 8.80, 8.20, 7.85],
    tag: { es: '↓ 5% hoy', en: '↓ 5% today' },
    trend: 'down',
  },
  pan: {
    id: 'pan', category: 'frescos',
    name: { es: 'Pan de pueblo', en: 'Country bread' },
    unit: { es: '500 g', en: '500 g' },
    emoji: '🍞',
    prices: { merc: 1.40, carr: 1.55, lidl: 1.30, dia: 1.45, eci: 2.20, amz: 1.80, sco: 1.60 },
    history: [1.40, 1.42, 1.40, 1.38, 1.40, 1.40],
  },
  detergente: {
    id: 'detergente', category: 'limpieza',
    name: { es: 'Detergente líquido', en: 'Laundry detergent' },
    unit: { es: '40 lavados', en: '40 washes' },
    emoji: '🧴',
    prices: { merc: 6.95, carr: 7.40, lidl: 6.50, dia: 7.10, eci: 8.20, amz: 7.60, sco: 7.80 },
    history: [7.20, 7.15, 7.10, 7.05, 7.00, 6.95],
    whiteLabel: { name: { es: 'Bosque Verde eco', en: 'Bosque Verde eco' }, save: 2.10 },
    offer: { es: '3×2 esta semana', en: '3-for-2 this week' },
    tag: { es: 'Oferta', en: 'On offer' },
  },
  huevos: {
    id: 'huevos', category: 'frescos',
    name: { es: 'Huevos camperos', en: 'Free-range eggs' },
    unit: { es: '12 u', en: '12 ct' },
    emoji: '🥚',
    prices: { merc: 3.25, carr: 3.45, lidl: 2.99, dia: 3.30, eci: 4.10, amz: 3.80, sco: 3.60 },
    history: [3.10, 3.15, 3.20, 3.22, 3.24, 3.25],
  },
  yogur: {
    id: 'yogur', category: 'frescos',
    name: { es: 'Yogur natural', en: 'Plain yogurt' },
    unit: { es: '8 × 125 g', en: '8 × 125 g' },
    emoji: '🥣',
    prices: { merc: 1.85, carr: 2.10, lidl: 1.70, dia: 1.95, eci: 2.60, amz: 2.20, sco: 2.30 },
    history: [1.90, 1.88, 1.86, 1.85, 1.85, 1.85],
    whiteLabel: { name: { es: 'Hacendado natural', en: 'Hacendado plain' }, save: 0.45 },
  },
  papel: {
    id: 'papel', category: 'limpieza',
    name: { es: 'Papel higiénico', en: 'Toilet paper' },
    unit: { es: '12 rollos', en: '12 rolls' },
    emoji: '🧻',
    prices: { merc: 4.95, carr: 5.40, lidl: 4.60, dia: 5.10, eci: 6.20, amz: 5.80, sco: 5.60 },
    history: [5.10, 5.05, 5.00, 4.98, 4.96, 4.95],
  },
  pasta: {
    id: 'pasta', category: 'despensa',
    name: { es: 'Espaguetis', en: 'Spaghetti' },
    unit: { es: '500 g', en: '500 g' },
    emoji: '🍝',
    prices: { merc: 0.95, carr: 1.10, lidl: 0.85, dia: 1.00, eci: 1.40, amz: 1.20, sco: 1.15 },
    history: [1.10, 1.05, 1.00, 0.98, 0.96, 0.95],
    whiteLabel: { name: { es: 'Hacendado', en: 'Hacendado' }, save: 0.25 },
  },
  cafe: {
    id: 'cafe', category: 'despensa',
    name: { es: 'Café en grano', en: 'Coffee beans' },
    unit: { es: '1 kg', en: '1 kg' },
    emoji: '☕',
    prices: { merc: 12.40, carr: 13.20, lidl: 11.90, dia: 12.80, eci: 15.60, amz: 13.80, sco: 13.50 },
    history: [10.80, 11.20, 11.60, 12.00, 12.20, 12.40],
    trend: 'up',
    tag: { es: '↑ 8% mes', en: '↑ 8% month' },
  },
  tomate: {
    id: 'tomate', category: 'frescos',
    name: { es: 'Tomate rama', en: 'Vine tomatoes' },
    unit: { es: '1 kg', en: '1 kg' },
    emoji: '🍅',
    prices: { merc: 2.15, carr: 2.40, lidl: 1.99, dia: 2.25, eci: 2.90, amz: 2.60, sco: 2.50 },
    history: [2.80, 2.60, 2.40, 2.30, 2.20, 2.15],
  },
  patatas: {
    id: 'patatas', category: 'frescos',
    name: { es: 'Patatas', en: 'Potatoes' },
    unit: { es: '2 kg', en: '2 kg' },
    emoji: '🥔',
    prices: { merc: 1.79, carr: 1.95, lidl: 1.69, dia: 1.85, eci: 2.40, amz: 2.10, sco: 2.00 },
    history: [1.60, 1.65, 1.70, 1.74, 1.78, 1.79],
  },
  cebolla: {
    id: 'cebolla', category: 'frescos',
    name: { es: 'Cebollas', en: 'Onions' },
    unit: { es: '1 kg', en: '1 kg' },
    emoji: '🧅',
    prices: { merc: 1.25, carr: 1.40, lidl: 1.15, dia: 1.30, eci: 1.80, amz: 1.55, sco: 1.45 },
    history: [1.30, 1.28, 1.26, 1.25, 1.25, 1.25],
  },
  ajo: {
    id: 'ajo', category: 'frescos',
    name: { es: 'Ajos', en: 'Garlic' },
    unit: { es: '3 cabezas', en: '3 heads' },
    emoji: '🧄',
    prices: { merc: 0.95, carr: 1.10, lidl: 0.89, dia: 1.00, eci: 1.40, amz: 1.20, sco: 1.10 },
    history: [1.00, 0.98, 0.97, 0.96, 0.95, 0.95],
  },
  arroz: {
    id: 'arroz', category: 'despensa',
    name: { es: 'Arroz bomba', en: 'Bomba rice' },
    unit: { es: '1 kg', en: '1 kg' },
    emoji: '🍚',
    prices: { merc: 2.45, carr: 2.70, lidl: 2.30, dia: 2.55, eci: 3.20, amz: 2.85, sco: 2.75 },
    history: [2.20, 2.28, 2.34, 2.40, 2.43, 2.45],
    whiteLabel: { name: { es: 'Hacendado bomba', en: 'Hacendado bomba' }, save: 0.40 },
  },
  pollo: {
    id: 'pollo', category: 'frescos',
    name: { es: 'Pechuga de pollo', en: 'Chicken breast' },
    unit: { es: '1 kg', en: '1 kg' },
    emoji: '🍗',
    prices: { merc: 6.50, carr: 6.95, lidl: 6.20, dia: 6.80, eci: 8.40, amz: 7.30, sco: 7.10 },
    history: [6.10, 6.20, 6.30, 6.40, 6.45, 6.50],
    tag: { es: 'Fresco hoy', en: 'Fresh today' },
  },
  pimiento: {
    id: 'pimiento', category: 'frescos',
    name: { es: 'Pimientos rojos', en: 'Red peppers' },
    unit: { es: '500 g', en: '500 g' },
    emoji: '🫑',
    prices: { merc: 1.95, carr: 2.20, lidl: 1.80, dia: 2.05, eci: 2.70, amz: 2.35, sco: 2.25 },
    history: [2.40, 2.20, 2.05, 1.99, 1.96, 1.95],
    seasonal: { es: 'En temporada — pimientos de la huerta', en: 'In season — local field peppers' },
    tag: { es: 'Temporada', en: 'In season' },
  },
  guisantes: {
    id: 'guisantes', category: 'despensa',
    name: { es: 'Guisantes', en: 'Peas' },
    unit: { es: '400 g', en: '400 g' },
    emoji: '🟢',
    prices: { merc: 1.35, carr: 1.50, lidl: 1.25, dia: 1.40, eci: 1.90, amz: 1.65, sco: 1.55 },
    history: [1.40, 1.38, 1.36, 1.35, 1.35, 1.35],
  },
  queso: {
    id: 'queso', category: 'frescos',
    name: { es: 'Queso curado', en: 'Aged cheese' },
    unit: { es: '300 g', en: '300 g' },
    emoji: '🧀',
    prices: { merc: 4.20, carr: 4.60, lidl: 3.95, dia: 4.40, eci: 5.60, amz: 4.90, sco: 4.75 },
    history: [4.00, 4.05, 4.10, 4.15, 4.18, 4.20],
    whiteLabel: { name: { es: 'Hacendado curado', en: 'Hacendado aged' }, save: 0.85 },
  },
  bacon: {
    id: 'bacon', category: 'frescos',
    name: { es: 'Bacon ahumado', en: 'Smoked bacon' },
    unit: { es: '200 g', en: '200 g' },
    emoji: '🥓',
    prices: { merc: 2.30, carr: 2.55, lidl: 2.10, dia: 2.40, eci: 3.10, amz: 2.70, sco: 2.60 },
    history: [2.25, 2.26, 2.28, 2.29, 2.30, 2.30],
  },
  nata: {
    id: 'nata', category: 'frescos',
    name: { es: 'Nata para cocinar', en: 'Cooking cream' },
    unit: { es: '200 ml', en: '200 ml' },
    emoji: '🥛',
    prices: { merc: 1.15, carr: 1.30, lidl: 1.05, dia: 1.20, eci: 1.60, amz: 1.40, sco: 1.30 },
    history: [1.15, 1.15, 1.15, 1.15, 1.15, 1.15],
  },
};

// Recipes — say a dish, the concierge derives the ingredient list (scaled to servings).
// Each ingredient: { id, per } where `per` is the qty of catalog units PER serving (can be fractional).
// add = ceil(per × servings), so the basket always carries whole purchasable units.
const RECIPES = {
  tortilla: {
    id: 'tortilla', emoji: '🍳', serves: 4, time: { es: '30 min', en: '30 min' },
    keywords: ['tortilla', 'tortilla de patata', 'tortilla española', 'spanish omelette', 'omelette', 'omelet'],
    name: { es: 'Tortilla de patatas', en: 'Spanish omelette' },
    desc: { es: 'El clásico de toda cocina española. Jugosa por dentro.', en: 'The staple of every Spanish kitchen. Runny in the middle.' },
    ingredients: [
      { id: 'huevos', per: 0.25 }, { id: 'patatas', per: 0.25 },
      { id: 'cebolla', per: 0.25 }, { id: 'aceite', per: 0.1 },
    ],
  },
  pastatomate: {
    id: 'pastatomate', emoji: '🍝', serves: 2, time: { es: '20 min', en: '20 min' },
    keywords: ['pasta', 'pasta con tomate', 'espagueti', 'spaghetti', 'pasta with tomato', 'macarrones'],
    name: { es: 'Pasta con tomate', en: 'Pasta with tomato' },
    desc: { es: 'Rápida, barata y siempre funciona entre semana.', en: 'Fast, cheap, and a reliable weeknight win.' },
    ingredients: [
      { id: 'pasta', per: 0.5 }, { id: 'tomate', per: 0.5 },
      { id: 'ajo', per: 0.15 }, { id: 'aceite', per: 0.1 },
    ],
  },
  carbonara: {
    id: 'carbonara', emoji: '🥓', serves: 2, time: { es: '25 min', en: '25 min' },
    keywords: ['carbonara', 'pasta carbonara'],
    name: { es: 'Pasta carbonara', en: 'Pasta carbonara' },
    desc: { es: 'Huevo, bacon y queso — sin nata de verdad, pero la añadimos por gusto.', en: 'Egg, bacon and cheese — purists skip cream, we keep it optional.' },
    ingredients: [
      { id: 'pasta', per: 0.5 }, { id: 'huevos', per: 0.17 },
      { id: 'bacon', per: 0.5 }, { id: 'queso', per: 0.33 }, { id: 'nata', per: 0.5 },
    ],
  },
  paella: {
    id: 'paella', emoji: '🥘', serves: 4, time: { es: '50 min', en: '50 min' },
    keywords: ['paella', 'arroz con pollo', 'arroz', 'rice with chicken'],
    name: { es: 'Paella de pollo', en: 'Chicken paella' },
    desc: { es: 'Domingo en familia. Arroz bomba, pollo y verduras de temporada.', en: 'Sunday with family. Bomba rice, chicken and seasonal veg.' },
    ingredients: [
      { id: 'arroz', per: 0.25 }, { id: 'pollo', per: 0.3 },
      { id: 'pimiento', per: 0.5 }, { id: 'tomate', per: 0.3 },
      { id: 'guisantes', per: 0.5 }, { id: 'ajo', per: 0.1 }, { id: 'aceite', per: 0.1 },
    ],
  },
  ensalada: {
    id: 'ensalada', emoji: '🥗', serves: 2, time: { es: '10 min', en: '10 min' },
    keywords: ['ensalada', 'salad', 'ensalada mixta'],
    name: { es: 'Ensalada de la huerta', en: 'Garden salad' },
    desc: { es: 'Tomate, cebolla, queso y un buen chorro de aceite.', en: 'Tomato, onion, cheese and a generous pour of olive oil.' },
    ingredients: [
      { id: 'tomate', per: 0.5 }, { id: 'cebolla', per: 0.25 },
      { id: 'queso', per: 0.33 }, { id: 'aceite', per: 0.1 },
    ],
  },
  desayuno: {
    id: 'desayuno', emoji: '🥐', serves: 2, time: { es: '15 min', en: '15 min' },
    keywords: ['desayuno', 'breakfast', 'tostadas', 'huevos revueltos', 'scrambled eggs'],
    name: { es: 'Desayuno completo', en: 'Full breakfast' },
    desc: { es: 'Pan, huevos, café y fruta para empezar bien el día.', en: 'Bread, eggs, coffee and fruit to start the day right.' },
    ingredients: [
      { id: 'pan', per: 0.5 }, { id: 'huevos', per: 0.25 },
      { id: 'cafe', per: 0.05 }, { id: 'naranjas', per: 0.5 },
    ],
  },
};


// Curated default scenario — pre-populated chat history demonstrating the flow.
// Starts empty; chat pushes items as the demo runs.
const SCENARIO_SCRIPT = [
  { type: 'user', text: { es: 'Ponme 3 litros de leche, un par de kilos de naranjas y pan', en: 'Give me 3 liters of milk, a couple kilos of oranges and bread' } },
  { type: 'parsing' },
  { type: 'ai-parsed', items: ['leche', 'naranjas', 'pan'] },
  { type: 'ai-context', productId: 'naranjas',
    text: { es: 'Las Navelina están en su pico de dulzor hasta abril — he elegido las mejores de temporada.',
            en: 'Navelinas are at peak sweetness through April — I picked the best in-season option.' } },
  { type: 'user', text: { es: 'Añade aceite de oliva y detergente', en: 'Add olive oil and detergent' } },
  { type: 'ai-parsed', items: ['aceite', 'detergente'] },
  { type: 'ai-context', productId: 'aceite',
    text: { es: 'El aceite ha bajado un 5% hoy — buen momento para stockear.',
            en: 'Olive oil dropped 5% today — good time to stock up.' } },
  { type: 'ai-qualify', productId: 'detergente',
    q: { es: 'Hay un 3×2 en el detergente que buscas. ¿Lo incluyo?',
         en: 'There\'s a 3-for-2 on the detergent you want. Include it?' },
    yes: { es: 'Sí, añádelo', en: 'Yes, add it' },
    no:  { es: 'Solo uno', en: 'Just one' } },
  { type: 'user', text: { es: 'Sí, añádelo', en: 'Yes, add it' }, auto: true },
  { type: 'ai-preference',
    q: { es: '¿Para esta cesta prefieres marca o precio más bajo?',
         en: 'For this basket do you prefer brand or lowest price?' },
    options: [
      { key: 'price', es: 'Precio', en: 'Price' },
      { key: 'brand', es: 'Marca',  en: 'Brand' },
      { key: 'balance', es: 'Equilibrio', en: 'Balance' },
    ] },
  { type: 'user', text: { es: 'Precio', en: 'Price' }, auto: true, pref: 'price' },
  { type: 'ai-subs', items: ['leche', 'yogur', 'pasta'] },
  { type: 'ai-summary' },
];

const CATEGORY_META = {
  frescos:  { es: 'Frescos',  en: 'Fresh',    dot: 'oklch(0.70 0.14 140)' },
  despensa: { es: 'Despensa', en: 'Pantry',   dot: 'oklch(0.72 0.13 60)'  },
  limpieza: { es: 'Limpieza', en: 'Cleaning', dot: 'oklch(0.68 0.12 240)' },
};

Object.assign(window, { STORES, CATALOG, SCENARIO_SCRIPT, CATEGORY_META, RECIPES });
